---
galaxy_info:
  author: "{{ company_name }}"
  description: "Pyroscope continuous profiling"
  license: "Proprietary"
  min_ansible_version: 2.9
  galaxy_tags: [pyroscope, profiling, observability]
dependencies:
  - docker
