---
- name: Installeer PostgreSQL Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v0.14.0/postgres_exporter-0.14.0.linux-{{ arch_map[ansible_architecture] }}.tar.gz"
    dest: "/tmp/postgres_exporter.tar.gz"
  tags: [monitoring]

- name: Extract PostgreSQL Exporter
  ansible.builtin.unarchive:
    src: "/tmp/postgres_exporter.tar.gz"
    dest: /tmp/
    remote_src: yes
  tags: [monitoring]

- name: Install PostgreSQL Exporter
  ansible.builtin.copy:
    src: "/tmp/postgres_exporter-0.14.0.linux-{{ arch_map[ansible_architecture] }}/postgres_exporter"
    dest: "/usr/local/bin/postgres_exporter"
    mode: '0755'
    remote_src: yes
  tags: [monitoring]

- name: Create PostgreSQL Exporter systemd service
  ansible.builtin.template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    mode: '0644'
  notify: restart postgres_exporter
  tags: [monitoring]

- name: Start and enable PostgreSQL Exporter
  ansible.builtin.systemd:
    name: postgres_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [monitoring]

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/postgres_exporter.tar.gz"
    - "/tmp/postgres_exporter-0.14.0.linux-{{ arch_map[ansible_architecture] }}"
  tags: [monitoring]
