---
- name: Laad bonding kernel module
  ansible.builtin.modprobe:
    name: bonding
    state: present

- name: Configureer bonding module options
  ansible.builtin.copy:
    dest: /etc/modprobe.d/bonding.conf
    content: |
      alias bond0 bonding
      options bonding mode={{ network_bonding_mode }} miimon={{ network_bonding_miimon }}
    mode: '0644'

- name: Configureer bond interface
  ansible.builtin.template:
    src: bond_debian.j2
    dest: /etc/network/interfaces.d/bond0
    mode: '0644'
  notify: restart networking
