---
- name: Configureer NetworkManager (RedHat)
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: yes

- name: Configureer interface specific files
  ansible.builtin.template:
    src: interface_redhat.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.name }}"
    mode: '0644'
  loop: "{{ network_interfaces }}"
  when: network_interfaces | length > 0
  notify: restart networking
