---
galaxy_info:
  author: "{{ company_name }}"
  description: "Neo4j graph database"
  license: "Proprietary"
  min_ansible_version: 2.9
  galaxy_tags: [neo4j, database, graph]
dependencies:
  - docker
