---
- name: Voeg ClickHouse GPG key toe
  ansible.builtin.apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8919F6BD2B48D754
    state: present

- name: Voeg ClickHouse repository toe
  ansible.builtin.apt_repository:
    repo: "deb https://packages.clickhouse.com/deb stable main"
    state: present
    update_cache: yes

- name: Installeer ClickHouse
  ansible.builtin.apt:
    name:
      - clickhouse-server
      - clickhouse-client
    state: present
