---
# =============================================================================
# MONITORING ROLE VARIABELEN
# =============================================================================

monitoring_prerequisites:
  Debian:
    - wget
    - curl
    - tar
    - adduser
    - libfontconfig
    - libfreetype6
    - libpng16-16
  RedHat:
    - wget
    - curl
    - tar
    - fontconfig
    - freetype
    - libpng
  Suse:
    - wget
    - curl
    - tar
    - fontconfig
    - freetype2
    - libpng16-16
  Archlinux:
    - wget
    - curl
    - tar
    - fontconfig
    - freetype2
    - libpng
  Alpine:
    - wget
    - curl
    - tar
    - fontconfig
    - freetype
    - libpng

# Versies
prometheus_version: "2.48.0"
node_exporter_version: "1.7.0"
cadvisor_version: "0.49.0"
grafana_version: "10.2.3"
loki_version: "2.9.4"
promtail_version: "2.9.4"
alertmanager_version: "0.26.0"

# Architectuur mapping
arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armv7
