---
- name: Configureer auditd (Debian)
  ansible.builtin.template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    mode: '0640'
  notify: restart auditd

- name: Configureer audit rules
  ansible.builtin.template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    mode: '0640'
  notify: restart auditd
