---
- name: Installeer Vagrant via package manager
  ansible.builtin.dnf:
    name: vagrant
    state: present
  ignore_errors: yes

- name: Fallback naar directe download
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_linux_{{ arch_map[ansible_architecture] }}.rpm"
    dest: "/tmp/vagrant.rpm"
  when: vagrant_install_failed | default(false)

- name: Installeer Vagrant via rpm
  ansible.builtin.dnf:
    name: "/tmp/vagrant.rpm"
    state: present
  when: vagrant_install_failed | default(false)
