---
galaxy_info:
  author: "{{ company_name }}"
  description: "Terraform Infrastructure as Code"
  license: "Proprietary"
  min_ansible_version: 2.9
  galaxy_tags: [terraform, iac, hashicorp]
dependencies: []
