---
# =============================================================================
# POSTGRESQL ROLE VARIABELEN
# =============================================================================

postgresql_packages:
  Debian:
    - postgresql-15
    - postgresql-client-15
    - postgresql-contrib-15
    - libpq-dev
    - python3-psycopg2
  RedHat:
    - postgresql-server
    - postgresql-contrib
    - postgresql
    - python3-psycopg2
  Suse:
    - postgresql15-server
    - postgresql15
    - python3-psycopg2
  Archlinux:
    - postgresql
    - python-psycopg2
  Alpine:
    - postgresql15
    - postgresql15-contrib
    - py3-psycopg2

postgresql_service:
  Debian: postgresql
  RedHat: postgresql
  Suse: postgresql
  Archlinux: postgresql
  Alpine: postgresql

postgresql_config_path:
  Debian: /etc/postgresql/15/main
  RedHat: /var/lib/pgsql/data
  Suse: /var/lib/pgsql/data
  Archlinux: /var/lib/postgres/data
  Alpine: /var/lib/postgresql/15/data

postgresql_data_dir:
  Debian: /var/lib/postgresql/15/main
  RedHat: /var/lib/pgsql/data
  Suse: /var/lib/pgsql/data
  Archlinux: /var/lib/postgres/data
  Alpine: /var/lib/postgresql/15/data

postgresql_bin_path:
  Debian: /usr/lib/postgresql/15/bin
  RedHat: /usr/bin
  Suse: /usr/bin
  Archlinux: /usr/bin
  Alpine: /usr/lib/postgresql/15/bin
