---
- name: Download Puppet repository
  ansible.builtin.get_url:
    url: "https://yum.puppet.com/puppet8-release-el-{{ ansible_distribution_major_version }}.noarch.rpm"
    dest: "/tmp/puppet-release.rpm"

- name: Installeer Puppet repository
  ansible.builtin.dnf:
    name: "/tmp/puppet-release.rpm"
    state: present

- name: Installeer Puppet
  ansible.builtin.dnf:
    name: puppet-agent
    state: present
