---
- name: Download Chef installer
  ansible.builtin.get_url:
    url: "https://packages.chef.io/files/stable/chef/18.0.0/ubuntu/22.04/chef_18.0.0-1_amd64.deb"
    dest: "/tmp/chef.deb"
  ignore_errors: yes

- name: Installeer Chef
  ansible.builtin.apt:
    deb: "/tmp/chef.deb"
    state: present
