---
galaxy_info:
  author: "{{ company_name }}"
  description: "Thanos Prometheus HA and long-term storage"
  license: "Proprietary"
  min_ansible_version: 2.9
  galaxy_tags: [thanos, prometheus, monitoring, ha]
dependencies:
  - docker
