---
galaxy_info:
  author: "{{ company_name }}"
  description: "ArangoDB multi-model database"
  license: "Proprietary"
  min_ansible_version: 2.9
  galaxy_tags: [arangodb, database, multi-model]
dependencies:
  - docker
