---
- name: '{{ ansible_os_family }} | Voeg Kubernetes repository toe'
  ansible.builtin.include_tasks: "repo_{{ ansible_os_family | lower }}.yml"
  tags: [packages]

- name: '{{ ansible_os_family }} | Installeer Kubernetes packages'
  ansible.builtin.package:
    name: "{{ kubernetes_packages[ansible_os_family] }}"
    state: present
  tags: [packages]

- name: '{{ ansible_os_family }} | Hold Kubernetes packages (Debian/RedHat)'
  ansible.builtin.shell: |
    apt-mark hold kubelet kubeadm kubectl
  when: ansible_os_family in ['Debian']
  tags: [packages]

- name: '{{ ansible_os_family }} | Start en enable kubelet'
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [packages]
