---
redis_port: 6379
redis_password: "{{ vault_redis_password }}"
redis_maxmemory: "2gb"
redis_maxmemory_policy: "allkeys-lru"
redis_appendonly: "yes"
redis_save:
  - "900 1"
  - "300 10"
  - "60 10000"
redis_monitoring_enabled: true
redis_monitoring_port: 9121
