---
galaxy_info:
  author: "{{ company_name }}"
  description: "Zabbix enterprise monitoring"
  license: "Proprietary"
  min_ansible_version: 2.9
  galaxy_tags: [zabbix, monitoring, enterprise]
dependencies:
  - docker
