---
- name: Voeg Docker GPG key toe
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Voeg Docker repository toe
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_arch[ansible_architecture] }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Docker architecture mapping
  ansible.builtin.set_fact:
    docker_arch:
      x86_64: amd64
      aarch64: arm64
      armv7l: armhf
