---
galaxy_info:
  author: "{{ company_name }}"
  description: "Falco runtime security"
  license: "Proprietary"
  min_ansible_version: 2.9
  galaxy_tags: [falco, security, runtime]
dependencies:
  - docker
