---
- name: restart postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service[ansible_os_family] }}"
    state: restarted

- name: reload postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service[ansible_os_family] }}"
    state: reloaded
